### ISSUE TITLE
Path to place produced gridpacks

### ISSUE THREAD

**Issue by sihyunjeon** [cms-PdmV/GridpackMachine#2]

**Comment by sihyunjeon** [comment]
@agrohsje

**Comment by sihyunjeon** [comment]
so /cmvfs/blahblah/<CampaignName>/<Process>/<Process-Setting>_tarball.tar.gz looks ok for you Alex?

**Comment by agrohsje** [comment]
what is blabla ? nothing relevant? so the slc7 blabla is gone?

**Comment by sihyunjeon** [comment]
i won't expect people to use slc6 now
and at least slc6 gridpacks are executed in slc7 so it's not unsafe to assume slc7 compatible

**Comment by agrohsje** [comment]
and the info is given in the gridpack as they are selfcontained now. so nothing to worry about.

**Comment by sihyunjeon** [comment]
So the plan is to make a genproductions branch with campaign name (which shows it's stable for that campaign). We can `git clone` the branch with campaign name for production and use the same campaign name to define the path to the gridpacks in `cvmfs`

**Comment by sihyunjeon** [comment]
We have to check if pdmvserv has write permissions in /eos/ area (also permission to make directory)

**Comment by sihyunjeon** [comment]
@agrohsje this is given by gen convenors right?

**Comment by agrohsje** [comment]
/eos/store/group/phys_generator/cvmfs/gridpacks/ is handled via  egroup cms-eos-pag-gen which is done by gen l2.

**Comment by sihyunjeon** [comment]
@agrohsje @jordan-martins

**Comment by sihyunjeon** [comment]
Also need to think about how to create the repository in
/cvmfs/cms.cern.ch/phys_generator/gridpacks/

"pdmvserv" should need to create a directory before starting the gridpacks so that it doesn't get lost.

**Comment by sihyunjeon** [comment]
wrote some stupid script to deal with this issue already. closing the issue

@cvico @agrohsje 

https://github.com/cms-PdmV/GridpackFiles/blob/master/Validation/makeDirs.py
